name: Publish NPM package
on:
  release:
    types: [created]
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npx nx affected -t lint --parallel=3
      - run: npm run build
      - name: Publish to npm registry
        working-directory: ./dist/publish-gitlab-release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
